### ISSUE TITLE
Can't run Plutus Pioneer Program

### ISSUE THREAD

**Issue by davidls99** [edwint88/plutus-vm#2]
Thx for making the vagrant image. I have the Playground server and client working so far. But I can't get the pioneer program to work properly. It fails on the error below after running "cabal build".

Specifically: 
`[__2] fail (backjumping, conflict set: plutus-contract, row-types)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: playground-common, plutus-contract,
row-types`

I'm trying to get started learning how to use Plutus, but have a hard time getting started. Any help would be welcome.

For full output see below:
`[nix-shell:~/plutus/git/plutus-pioneer-program/code/week01]$ cabal build
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.RemoteRepo {remoteRepoName = RepoName
"hackage.haskell.org", remoteRepoURI = http://hackage.haskell.org/,
remoteRepoSecure = Just True, remoteRepoRootKeys =
["***"],
remoteRepoKeyThreshold = 3, remoteRepoShouldTryHttps = True}
Warning: Requested index-state 2021-02-24T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state ().
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: playground-common-0.1.0.0 (user goal)
[__1] trying: row-types-1.0.1.0/installed-6TxB7fff4fwB34s75ahtFk (dependency
of playground-common)
[__2] next goal: plutus-contract (user goal)
[__2] rejecting: plutus-contract-0.1.0.0 (conflict:
row-types==1.0.1.0/installed-6TxB7fff4fwB34s75ahtFk, plutus-contract =>
row-types<1.0)
[__2] fail (backjumping, conflict set: plutus-contract, row-types)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: playground-common, plutus-contract,
row-types`

**Comment by edwint88** [comment]
I'm seeing that you want to run week01, for that you should follow the official plutus pioneer program to see the cabal version and the git commit number. In addition check: https://docs.plutus-community.com/docs/setup/CabalBuild.html
I think the right checkout is:  `git checkout 3746610e53654a1167aeb4c6294c6096d16b0502` (check with the discord channel too).
After the first week some major things were changed and this may be the reason that this doesn't work directly with week01.
Hope this helps!
